### ISSUE TITLE
Add possibility to support higher FPS

### ISSUE THREAD

**Issue by deden** [Mijick/CameraView#28]

**Comment by FulcrumOne** [comment]
hey @deden,

The feature was implemented in the `patch-2.1.0` branch.

**Comment by clbemre** [comment]
@FulcrumOne Hello, I have read Readme file, but I don't understand frameRate: 25, what does it mean? what is range? I don't know details for camera :)

**Comment by clbemre** [comment]
@FulcrumOne What was the default frame rate before adding this setting?

**Comment by FulcrumOne** [comment]
Hey @clbemre, sorry didn't notice your comment.

**Frame rate** means the number of frames in a second of video (including camera preview). The default is (and was) 30.

**Comment by clbemre** [comment]
@FulcrumOne Thank you.
