### ISSUE TITLE
Package Resolution Fails when attempting to add dependency with SPM

### ISSUE THREAD

**Issue by dimitri-nik** [Mijick/CameraView#29]
Hey! I've got an issue while trying to add the CameraView package to my project using Swift Package Manager. The package resolution is failing with the following error:

Failed to resolve dependencies Dependencies could not be resolved because root depends on 'cameraview' 1.2.0..<2.0.0.
unexpectedly did not find the new dependency in the package graph: sourceControl(identity: cameraview, location: SwiftPM.SPMPackageDependency.Sourc...

Xcode version 15.4
swift 5.0
ios 17.0

I tried clearing derived data and package caches
I recently added your PopUp package successfully

Not sure what else to try thanks!

**Comment by guytepper** [comment]
Make sure to add https://github.com/Mijick/Timer as a dependency.

**Comment by dimitri-nik** [comment]
I added Timer as a dependency, but I'm still seeing the same issue 🤔

**Comment by guytepper** [comment]
Can you post the full error you're getting? The error in your main post is truncated

**Comment by FulcrumOne** [comment]
Sorry guys, I'll try to get back to this thread at the end of the day, I'm super busy fixing the problems from #26

**Comment by dimitri-nik** [comment]
Hey no issue building the app because I haven't added the package yet. The issue arises when I try to add the package through swift package manager in xcode. I started a fresh project added the Timer package successfully but when I try to add the CameraView this is what I see from spm:
<img width="915" alt="Screenshot 2024-07-08 at 12 26 11 PM" src="https://github.com/Mijick/CameraView/assets/65304158/70d35f29-84fc-4451-b9cf-440620808ee2">

**Comment by FulcrumOne** [comment]
ok, I was able to reproduce it.  It seems that the problem only occurs in this configuration when importing the package:
![CleanShot 2024-07-08 at 23 59 41](https://github.com/Mijick/CameraView/assets/23524947/92cf4fc7-dce9-4bf5-8d50-9492c730ba34)

To fix this, just select branch `main` here
![CleanShot 2024-07-08 at 23 59 51](https://github.com/Mijick/CameraView/assets/23524947/4620d7bb-53d2-4acf-9c19-c7fe51b064f0)


Let me know if it solved your problem 😉

**Comment by dimitri-nik** [comment]
This solved my problem thank you!! 🙌

**Comment by FulcrumOne** [comment]
@dimitri-nik, glad to hear it!

@guytepper thanks for your help as well! 😉

**Comment by guytepper** [comment]
@FulcrumOne isn't the issue with this solution, to get the latest commits from the main branch, that it enforces the library to be updated even if that's not intentional? For example, breaking changes could be introduced.

**Comment by FulcrumOne** [comment]
@guytepper unfortunately it slipped my mind when publishing this update and I'm very sorry for this😕

I promise to introduce the fix in the upcoming update.

Thanks for your comment and have a good day,
Tomasz

**Comment by FulcrumOne** [comment]
@guytepper [here's](https://mijick.notion.site/ed227d35caa249e4a04e3a1e93129576?v=013c9f8962744b9f84bf4b3a544196db) the roadmap for this library.

Feel free to create a ticket if you need some new feature to be introduced 😉

**Comment by FulcrumOne** [comment]
@guytepper, @dimitri-nik

Version 2.1.0 resolves this problem.
