### ISSUE TITLE
Add an option to modify default camera view

### ISSUE THREAD

**Issue by belyakov-am** [Mijick/CameraView#33]
It would be nice to be able to hide some buttons from the [default camera view](https://github.com/Mijick/CameraView/blob/main/Sources/Internal/Views/Default/DefaultCameraView.swift)

Specifically an option to hide [photo / video output buttons](https://github.com/Mijick/CameraView/blob/main/Sources/Internal/Views/Default/DefaultCameraView.swift#L67)

**Comment by FulcrumOne** [comment]
Hey @belyakov-am,

Your request was added to our [roadmap](https://mijick.notion.site/ed227d35caa249e4a04e3a1e93129576?v=013c9f8962744b9f84bf4b3a544196db&pvs=74)

Thanks for this comment and have a nice day!

**Comment by belyakov-am** [comment]
Hey @FulcrumOne 

Amazing, thanks. Have a nice day too!

**Comment by davit-b** [comment]
+1 on this. Just hiding some of the fields in the Camera View would be great. I want to disable taking photos, and disable allowing rotating the camera to the front.

**Comment by davit-b** [comment]
Is there a workaround in the meantime? I tried to build a Custom CameraView that looks identical to the DefaultCameraView expect with a few customizations, but many of the dependent structs are marked `fileinternal` and the bridging is becoming a giant mess.

I don't want to resort to cloning the library and import it as a local dependency just yet.

**Comment by davit-b** [comment]
@FulcrumOne 

Oh, if you could that we be amazing. The default UI is really great! So naturally I just want to modify it, that would save me a lot of time.

**Comment by splons** [comment]
Another vote for this one, thank you for considering it.

I have an application where I just want to take photos (no videos), so this would support that nicely.

**Comment by FulcrumOne** [comment]
Hey guys,

FYI, I'm having some delays at work, so unfortunately I have to postpone the start of the work to Friday.
Apologies for this, I will keep you in the loop.

Best regards,
Tomasz

**Comment by davit-b** [comment]
Ok, thank you for the update.

**Comment by FulcrumOne** [comment]
I'm starting my work and will try to deliver something today.

**Comment by FulcrumOne** [comment]
@davit-b, @splons, @belyakov-am

The feature was implemented in branch named 'patch-2.1.0'. Could you check it out and let me know if it works as expected?

Here is an example of how to use it:
```Swift
MCameraController(manager: manager)
    .cameraScreen {
        DefaultCameraView(cameraManager: $0, namespace: $1, closeControllerAction: $2)
            .torchButtonVisible(false)
            .outputTypePickerVisible(false)
            .flipButtonVisible(false)
    }
```

**Comment by davit-b** [comment]
@FulcrumOne 

Just implemented, it meets all my needs. Thank you so much!!

**Comment by FulcrumOne** [comment]
Thank you too! I'm closing the issue then.

**Comment by splons** [comment]
Thank you for the fast work on this request!

The `outputTypePickerVisible` modifier does exactly what I need -- perfect.

I tested the other modifiers from your sample code above and found that adding `.flipButtonVisible(false)` does not hide the button to flip from back to front cameras (assuming that is what is intended).

**Comment by FulcrumOne** [comment]
Hey @splons,

The Flip button is located on the navigation bar - it essentially flips the view from camera horizontally.
The button you mentioned is hidden with the `cameraPositionButtonVisible` function. 

Have a nice day,
T.K.

**Comment by tiendq** [comment]
> @davit-b, @splons, @belyakov-am
> 
> The feature was implemented in branch named `patch-2.1.0`. Could you check it out and let me know if it works as expected?
> 
> Here is an example of how to use it:
> 
> ```swift
> MCameraController(manager: manager)
>     .cameraScreen {
>         DefaultCameraView(cameraManager: $0, namespace: $1, closeControllerAction: $2)
>             .torchButtonVisible(false)
>             .outputTypePickerVisible(false)
>             .flipButtonVisible(false)
>     }
> ```

Hi, could you give me an example for newly changes [MCameraScreen](https://github.com/Mijick/Camera/wiki/Customizing-MCamera-Screens)? I don't know how to make it work to get same result as I could with previous sample app as below. It's just turning on/off a few options so I think I don't need to define a new custom struct.

```
MCameraController(manager: manager)
        .cameraScreen {
          // Change default camera view (with on/off options)
          DefaultCameraView(cameraManager: $0, namespace: $1, closeControllerAction: $2)
            .cameraPositionButtonVisible(false)
            .flipButtonVisible(false)
            .outputTypePickerVisible(false)
        }
```

**Comment by FulcrumOne** [comment]
@tiendq, you can see the methods available in the `Public+UI+DefaultCameraScreen` file; in a nutshell they have been renamed from (...)Visible to (...)Allowed

**Comment by tiendq** [comment]
> @tiendq, you can see the methods available in the `Public+UI+DefaultCameraScreen` file; in a nutshell they have been renamed from (...)Visible to (...)Allowed

Thank you, it works now.

BTW, I believe there is a very minor issue in [this line](https://github.com/Mijick/Camera/blob/main/Sources/Public/UI/Public%2BUI%2BMCameraScreen.swift#L26), it should be `CustomCameraScreen` (and not `CustomCameraErrorScreen`).

**Comment by ronaldho** [comment]
I'm a bit confused on how to set this up after 3.0 patch launched. In my content view, this is what I've tried doing but it doesn't seem to be right.

```
struct ContentView: View {
//    @State private var isSheetPresented: Bool = false
    @ObservedObject var cameraManager: CameraManager
    let namespace: Namespace.ID
    let closeMCameraAction: () -> ()
    var body: some View {
    MCamera()
            .setCameraScreen(DefaultCameraScreen(cameraManager: cameraManager, namespace: namespace, closeMCameraAction: <#T##() -> Void#>))
                
            
            // MUST BE CALLED!
            .startSession()
        
    }
}

```

Thanks in advance for the help!
