### ISSUE TITLE
why prview c'rashed？

### ISSUE THREAD

**Issue by Wechat-ggGitHub** [Mijick/CameraView#39]
xxx crashed due to an uncaught exception`NSInvalidArgumentException`. Reason: ***[AVCapturePhotoOutputcapturePhotoWithSettings:delegate:] No active andenabled video connection.

**Comment by FulcrumOne** [comment]
Hey, could you please provide me with more details? Like when it happened and on which iOS version.

Thanks a million,
T.K.
