### ISSUE TITLE
[BUG] Camera/Preview Rotation

### ISSUE THREAD

**Issue by xKean** [Mijick/CameraView#40]
Hi!
There is a problem when locking device rotation.
If you lock device rotation on the iPhone but not in the controller, the grid and all icons rotate like expected.
But if you take the picture, the picture will not be rotated in the preview tab.
I'd expect every image to be rotated to the screen rotation it was taken with.

If you take a picture with controller-rotation disabled via ApplicationDelegation the problem is the same!
A way to lock the UI apart from the actual picture rotation would be amazing!
This would enable us to take pictures like this (I really love the semi-rotated default view)
![IMG_5199](https://github.com/user-attachments/assets/499bf39c-897e-48e9-8c2a-47c8c8698409)
and instantly see them in the right orientation
![IMG_5200](https://github.com/user-attachments/assets/a2aae087-e5cb-4cf2-ad8a-67c2a0f2550b)
(imagine this rotated :) )

I'd love to see those improvements!

**Comment by FulcrumOne** [comment]
Hey @xKean,

The issue should be fixed in the `patch-2.1.1` branch
