### ISSUE TITLE
set platforms to .iOS(.v17)

### ISSUE THREAD

**Issue by madhavgharmalkar** [Mijick/CameraView#45]
Great library! However I'm running into an issue when building:

```
❌ Tuist/.build/checkouts/CameraView/Sources/Internal/Extensions/UIImageView++.swift:14:29: 'ImageResource' is only available in iOS 17.0 or newer
❌ Tuist/.build/checkouts/CameraView/Sources/Internal/Extensions/UIImageView++.swift:15:41: 'init(resource:)' is only available in iOS 17.0 or newer
```

this seems to be the case because the swift library is using iOS 17 features, but SPM states that the library works with iOS 14

**Comment by MartinStrambach** [comment]
I opened a similar issue in Tuist repo https://github.com/tuist/tuist/issues/6641.
It doesn't synthesise ImageResource correctly. The target version isn't an issue in this case.

**Comment by pepicrft** [comment]
I'd suggest that we close the issue here since it's unrelated to this package. Thoughts @MartinStrambach ?

**Comment by madhavgharmalkar** [comment]
Agree, I'll close it out. Thank you guys!
