### ISSUE TITLE
[BUG] Icons won't load in 18.1

### ISSUE THREAD

**Issue by tcollins590** [Mijick/CameraView#48]
Some reason iOS 18.1 coupled with xcode 16 broke loading icons.

```No image named 'icon-change-camera' found in asset catalog for /private/var/containers/Bundle/Application/ADFEC06D-2C65-4555-B90C-0CD0526F1664/CameraView-Demo.app```

**Comment by voiceusa01** [comment]
Should be fixed soon as they have the stable release coming soon to iOS 18.1
________________________________
From: Tyler Collins ***@***.***>
Sent: Monday, September 23, 2024 2:12 PM
To: Mijick/CameraView ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Mijick/CameraView] Icons won't load in 18.1 (Issue #48)


Some reason iOS 18.1 coupled with xcode 16 broke loading icons.

No image named 'icon-change-camera' found in asset catalog for /private/var/containers/Bundle/Application/ADFEC06D-2C65-4555-B90C-0CD0526F1664/CameraView-Demo.app

**Comment by FulcrumOne** [comment]
Hey,

I'll handle it next week hopefully as I'm working on [PopupView](https://github.com/Mijick/PopupView) currently.

**Comment by FulcrumOne** [comment]
Hey,

Unfortunately I won't be able to fix it before I finish my work on PopupView (in 3-4 weeks).

Super sorry for this, but I totally miscalculated the time I needed for that library.
