### ISSUE TITLE
How can I skip camera preview screen?

### ISSUE THREAD

**Issue by tiendq** [Mijick/CameraView#51]
After an image is captured I want camera screen is disappeared and go back to my app. But I don't know how to skip preview screen which requires one more tap (to Accept button).

Below is my code (skipped unrelated code), I tried to remove `returnToCameraView` and both `true/false` values but no option works.

```swift
MCameraController(manager: manager)
        .afterMediaCaptured {
          $0.returnToCameraView(false)
            .closeCameraController(true)
        }
```

Thank you,

**Comment by Andreasgejlm** [comment]
You can set `.mediaPreviewScreen(nil)` as a modifier on MCameraController.

**Comment by tiendq** [comment]
> You can set `.mediaPreviewScreen(nil)` as a modifier on MCameraController.

It works, thank you.
