### ISSUE TITLE
Can I change focus shape?

### ISSUE THREAD

**Issue by tiendq** [Mijick/CameraView#53]
I noticed that focus shape is a rounded corner square and not just a square in built-in camera. I do know there is no big issue here but I think it'd be better if an app uses default UI where applicable, especially if your app is not an enhanced camera app.

Thank you,

**Comment by FulcrumOne** [comment]
Hey. There is a way to do this - when declaring `CameraManager` you can select your own `focusImage`. Sorry for no documentation for this library; it will be changed soon.
