### ISSUE TITLE
How to pin the mode to image or video and hide the mode switch buttons?

### ISSUE THREAD

**Issue by fyepi** [Mijick/CameraView#63]
Thanks for this great lib.

I am developing an app with this lib that I would need image capture only. I have removed ` .onVideoCaptured` but the switch buttons are still there and are still working. 

How to fix the mode to image and hide the mode switch buttons?

Thanks.

**Comment by fyepi** [comment]
I did a little hacking by modifying the source code in `DefaultCameraView.swift` to get it work temporarily. Obviously it should be through configuration or automatic detection if switching between image or video capture is necessary.

```
// MARK: - Configurables
extension DefaultCameraView { struct Config {
    var outputTypePickerVisible: Bool = false // <------------ hack
    var torchButtonVisible: Bool = true
    var captureButtonVisible: Bool = true
    var changeCameraButtonVisible: Bool = true
    var gridButtonVisible: Bool = true
    var flipButtonVisible: Bool = true
    var flashButtonVisible: Bool = true
}}
```

**Comment by FulcrumOne** [comment]
Hey @fyepi it's already implemented - take a look at this issue where I explain how to use it - https://github.com/Mijick/CameraView/issues/33#issuecomment-2253660864

However I do agree, I organised the public API in the worst and stupidest way possible, I'm working on it during this sprint to simplify it. 

Have a nice day,
Tomasz

**Comment by fyepi** [comment]
@FulcrumOne 

That works. Thanks
