### ISSUE TITLE
why frameRate can only be setted to 30 on iphone 13 pro max

### ISSUE THREAD

**Issue by LilKxG** [Mijick/CameraView#66]
but i can record video with 60 fps on other app 😭

log:CANNOT SETUP CAMERA: incorrectFrameRate

**Comment by FulcrumOne** [comment]
Hey @LilKxG,

I'm not sure about the current version, but in 3.0.0, which is expected to be released within a week, this will change.

However, please note that the maximum frame rate is strongly related to the resolution - for hd1920x1080 the maximum frame rate is 30 FPS, but if you downscale to hd1280x720 you can increase the frame rate to 60.
